### ISSUE TITLE
myPay reanalysis: Verify Abstract and Design

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/analysisteam#1]
Figure out if our take on the design of the study is on target and if our proposed analysis plan meets the policy needs of the study.

- [x] Discuss with Hyunsoo
- [x] Agree on analysis plan (with Hyunsoo and us)
   - [x] Learn about what comparisons are possible given the data

**Comment by PTesta** [comment]
Added a section and table trying to clarify the construction of the outcome variable and the possible comparisons groups, since we have reactivation data observed at multiple points in time.

**Comment by jwbowers** [comment]
The possible comparisons depend on what data is available. At the very least we want to compare all groups versus group 2 (baseline). Group 1 may or may not be useful --- if their outcomes are observed during the whole study, then we can use them as a kind of second control (or "natural" or "global" control). 

Also, with  # strata x # treatments x binary (or multinomial) outcome, the  [Cochran-Mantel-Haenszel](https://en.wikipedia.org/wiki/Cochran%E2%80%93Mantel%E2%80%93Haenszel_statistics) test suggests itself. And for rare outcomes, the version in the (coin package)[https://cran.r-project.org/web/packages/coin/index.html] is useful because it  does both asymptotic and approximative inference.

For a blocked continuous outcome or a binary outcome and binary treatment we can use `xBalance` in the `RItools` package or follow some of the ideas from (Lin, Green, and Coppock)[https://github.com/acoppock/Green-Lab-SOP].

**Comment by jwbowers** [comment]
A small todo: 
 - [ ] Reformat the Table 4 so that it is legible in HTML or PDF.

**Comment by jwbowers** [comment]
This has been done.
