### ISSUE TITLE
oneblast analyses next steps

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/analysisteam#4]
@PTesta The merging is basically done. Ready for analysis. Handing the analysis over to you for now. The basic analysis, using a generalized cochran mantel haenszel test is done. We now want to do the subsidiary analyses: 
- [x] estimate differences of proportions,
- [x] tests differences in the prespecified subgroups of treatments (probably using the CMH test again). 
- [x] Produce a simple visualization of differences among the treatment
- [x] Assess sensitivity of the results to different ways of distributing the unmatched subscribers into the batches. Here we see that there were 24 subscribers in the first batchday who were not matched to the experimental pool, and 6 in the second batchday.

```
batchday2
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16
  24    6   14   33   20   24   19   38    8   18    8   99   14   23   20   48
  17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32
  16   12   22   44   16   53   12   26   40   13   64   23   54   24   29   15
  33   34   35   36   37   38   39   40   41 <NA>
  52   10   11   65   22   25   40   10   81    0
```

Since we are not using other background data, one bound on the effect would take 24 members of the experimental pool who are currently scored as non-subscribers and call them subscribers in batchday 1. (We moved from 82 batches to 41 batchdays because the subscribers only have day of subscription recorded and not time and because most of the batches were sent two per day (all of them I think).).

**Comment by PTesta** [comment]
Just pushed some initial code that:

- Estimates difference of proportions; shows barplot with CIs for proportions
- Presents pairwise comparisons of each difference using a Tukey HSD test on the outcome, centered within each batch (is that right?)
- Conducts CMH tests (stratified by batch) for the three 3 subgroup comparisons. The tables now include the asymptotic test, the approximations using the coin package and the estimated common odds ratio (I had to hack mantelhaen.test() to get it to deal with large integers as numbers)
- An initial, clunky attempt at bounding the analysis by randomly reassign unmatched cases to subscribers within batch day. I'm going to let these run on a small number of simulations (100), check to make sure things look right, produce some figures and then compile with a larger number of simulations (1000? 5000?)

**Comment by nahiggins** [comment]
Link to the code/results?

**Comment by jwbowers** [comment]
Here are the results so far: http://htmlpreview.github.io/?https://github.com/sbstusa/oneblast/blob/master/oneblast_analysis.html. That file created by code in <https://github.com/sbstusa/oneblast/blob/master/oneblast_analysis.Rmd> .

**Comment by jwbowers** [comment]
- [ ] Sensitivity analysis should assign all unmatched people in a batch to treatment A...F one at a time across all batches to create a bound on the effect. (It is possible that the existing simulations could be turned to this use but I think that it will be easier to just bound the effects assuming homogeneity across batch.)

**Comment by jwbowers** [comment]
- [ ] Re-present proportion based analyses with batchday2 aligned outcomes. Although the batches are nearly the same size, I think that our standard practice should not ignore design features, especially ones where we could gain statistical power. In this case, the differences in estimated proportion subscribing will be small, but the CIs on the boxplots might change using aligned outcomes.

```
 table(wrkdat$batchday2)

    1     2     3     4     5     6     7     8     9    10    11    12    13
12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000
   14    15    16    17    18    19    20    21    22    23    24    25    26
12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000
   27    28    29    30    31    32    33    34    35    36    37    38    39
12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000 12000
   40    41
12000 11879
```

**Comment by jwbowers** [comment]
This analysis is now done.
