### ISSUE TITLE
SBA Pilot

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/analysisteam#8]
- [x] Graphic including time trend
- [x] Talk about start, end and mean of previous year as well as same month past year.

Shortening the form, starting with less sensitive information, and excluding some possibly sensitive information.

Collapse the A vs B comparison.

**Comment by PTesta** [comment]
Added github repo for figure https://github.com/sbstusa/sba

**Comment by jwbowers** [comment]
- [ ] Do a test of proportions (`prop.test`) converting during mar--may 2016 versus average of jan and feb 2016. Also test mar--may 2016 versus mar--may 2015. 
- [ ] Edit the Abtract (see Slack channel) to reflect p-values and confidence intervals.

**Comment by PTesta** [comment]
Made edits to abstract adding comparisons to three months before the change and three months a year before the change (in footnotes) with CIs and p values from prop test. Also updated the figures so both are showing percents.
